name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set execute permissions for mvnw
        run: chmod +x backend/mvnw

      - name: Build and test backend
        run: |
          cd backend
          ./mvnw clean package

      - name: List target directory
        run: |
          cd backend
          ls -la target

      - name: Build and test frontend
        run: |
          cd frontend
          npm ci
          npm test
          npm run build

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build --no-cache

      - name: Run Docker containers
        run: docker-compose -f docker-compose.yml up --build -d

      - name: View Docker logs
        run: docker-compose -f docker-compose.yml logs

      - name: Wait for containers to be ready
        run: sleep 30

      - name: Check container status
        run: docker-compose -f docker-compose.yml ps

      - name: Run backend tests in Docker
        run: docker-compose -f docker-compose.yml exec -T backend ./mvnw test

      - name: Inspect Docker container
        if: failure()
        run: docker inspect app_demo_marv_backend_1
