name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test backend
        run: |
          cd backend
          ./mvnw clean test

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Build and test frontend
        run: |
          cd frontend
          npm ci
          npm test
          npm run build

      - name: Build Docker image for frontend
        run: |
          cd /home/serious/Projects/Auto_projects/frontend
          docker build -t frontend-image .
