name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build and test backend
        run: |
          cd backend
          ./mvnw clean package

      - name: Build and test frontend
        run: |
          cd frontend
          npm ci
          npm test
          npm run build

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml build

      - name: Run Docker containers
        run: docker-compose -f docker-compose.yml up -d

      - name: Wait for containers to be ready
        run: sleep 30

      - name: Run backend tests in Docker
        run: docker-compose -f docker-compose.yml exec -T backend ./mvnw test
